name: test_package
description: A new Flutter package project.
version: 0.0.1
publish_to: https://premiumsarl.jfrog.io/artifactory/api/pub/math-pub
homepage: https://github.com/contactpkumara/test_package

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
